service: s3-example # NOTE: update this with your service name
provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1

  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 's3:GetObject'
      Resource: arn:aws:s3:::connect-storage-talk/*

functions:
  s3-event-example:
    handler: 01s3-trigger.example
    events:
      - s3:
          bucket: connect-storage-talk
          event: s3:ObjectCreated:*
          rules:
            - prefix: .csv